language: java
addons:
  sonarcloud:
    organization: "adioss-github"
jdk:
  - oraclejdk8

env:
  - NODE_VERSION=6.9.5
  - NPM_VERSION=3.10.10

before_install:
   - npm i -g npm@$NPM_VERSION

install:
  - nvm install $NODE_VERSION
  - npm install
  - npm install -g webpack

before_script:
  - nvm use $NODE_VERSION

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

