server:
    port: 8080

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 12345
            database: example

#metrics:
#    jmx.enabled: true
#    spark:
#        enabled: false
#        host: localhost
#        port: 9999
#    graphite:
#        enabled: false
#        host: localhost
#        port: 2003
#        prefix: example
#
#cache:
#    timeToLiveSeconds: 3600
#    hazelcast:
#        debug: true
#        stickySession: false
#        backupCount: 1
