server:
  port: 8080
cors:
  allowed:
    origins:
      - http://localhost:3000
      - http://localhost:8080
#spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#logging:
#  level.org.springframework.web: 'DEBUG'
#  level.org.springframework.security: 'DEBUG'
#  level.org.hibernate: 'DEBUG'